### ISSUE TITLE
 Add a new command for changing the password

### ISSUE THREAD

**Issue by marchesesimone** [wp-cli/super-admin-command#32]
Hello, 
I would like to contribute by inserting a new command that allows you to change the password of a single user.
Taking a cue from drush could be:
`wp super-admin upwd username --password = new_password`

Could it be interesting for you?
Thank you

**Comment by schlessera** [comment]
@marchesesimone There's nothing specific about the `super-admin` role when it comes to the password, it's still just a regular user.

What you want to achieve is already possible through the `user` command:
```
wp user update <username> --user_pass=<new_password>
```
