### ISSUE TITLE
Super admin issue in WordPress

### ISSUE THREAD

**Issue by Odeya-Pergament** [wp-cli/super-admin-command#56]
Hi
I'm trying to change the Super admin in the WordPress dashboard from the old admin to myself, but I don't get the email to confirmation. 

Please advise,

Thanks

Odeya

**Comment by danielbachhuber** [comment]
Hi @Odeya-Pergament,

GitHub issues are meant for reproducible bugs, enhancement requests, etc. for WP-CLI. We don't offer general WordPress support. For your particular issue, I'd recommend contacting your web host.
